/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkforceManagementRouteImport } from './routes/workforce-management'
import { Route as TimeOffManagementRouteImport } from './routes/time-off-management'
import { Route as TimeClockRouteImport } from './routes/time-clock'
import { Route as ShiftTradingRouteImport } from './routes/shift-trading'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmployeeSchedulingRouteImport } from './routes/employee-scheduling'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClockTokenRouteImport } from './routes/clock.$token'
import { Route as AuthenticatedWorksiteRouteImport } from './routes/_authenticated/worksite'
import { Route as AuthenticatedWhosInRouteImport } from './routes/_authenticated/whos-in'
import { Route as AuthenticatedTradesRouteImport } from './routes/_authenticated/trades'
import { Route as AuthenticatedTimeclockRouteImport } from './routes/_authenticated/timeclock'
import { Route as AuthenticatedTimecardsRouteImport } from './routes/_authenticated/timecards'
import { Route as AuthenticatedTimeOffRouteImport } from './routes/_authenticated/time-off'
import { Route as AuthenticatedSharedClockInRouteImport } from './routes/_authenticated/shared-clock-in'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScheduleTemplatesRouteImport } from './routes/_authenticated/schedule-templates'
import { Route as AuthenticatedScheduleSheetRouteImport } from './routes/_authenticated/schedule-sheet'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPunchCorrectionsRouteImport } from './routes/_authenticated/punch-corrections'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedOrganizationRouteImport } from './routes/_authenticated/organization'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAvailabilityRouteImport } from './routes/_authenticated/availability'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedAppRulesRouteImport } from './routes/_authenticated/app-rules'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedEmployeesJoinRequestsRouteImport } from './routes/_authenticated/employees.join-requests'

const WorkforceManagementRoute = WorkforceManagementRouteImport.update({
  id: '/workforce-management',
  path: '/workforce-management',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeOffManagementRoute = TimeOffManagementRouteImport.update({
  id: '/time-off-management',
  path: '/time-off-management',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeClockRoute = TimeClockRouteImport.update({
  id: '/time-clock',
  path: '/time-clock',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftTradingRoute = ShiftTradingRouteImport.update({
  id: '/shift-trading',
  path: '/shift-trading',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeSchedulingRoute = EmployeeSchedulingRouteImport.update({
  id: '/employee-scheduling',
  path: '/employee-scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClockTokenRoute = ClockTokenRouteImport.update({
  id: '/clock/$token',
  path: '/clock/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorksiteRoute = AuthenticatedWorksiteRouteImport.update({
  id: '/worksite',
  path: '/worksite',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWhosInRoute = AuthenticatedWhosInRouteImport.update({
  id: '/whos-in',
  path: '/whos-in',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradesRoute = AuthenticatedTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimeclockRoute = AuthenticatedTimeclockRouteImport.update({
  id: '/timeclock',
  path: '/timeclock',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimecardsRoute = AuthenticatedTimecardsRouteImport.update({
  id: '/timecards',
  path: '/timecards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimeOffRoute = AuthenticatedTimeOffRouteImport.update({
  id: '/time-off',
  path: '/time-off',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSharedClockInRoute =
  AuthenticatedSharedClockInRouteImport.update({
    id: '/shared-clock-in',
    path: '/shared-clock-in',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScheduleTemplatesRoute =
  AuthenticatedScheduleTemplatesRouteImport.update({
    id: '/schedule-templates',
    path: '/schedule-templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScheduleSheetRoute =
  AuthenticatedScheduleSheetRouteImport.update({
    id: '/schedule-sheet',
    path: '/schedule-sheet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPunchCorrectionsRoute =
  AuthenticatedPunchCorrectionsRouteImport.update({
    id: '/punch-corrections',
    path: '/punch-corrections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationRoute =
  AuthenticatedOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAvailabilityRoute =
  AuthenticatedAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRulesRoute = AuthenticatedAppRulesRouteImport.update({
  id: '/app-rules',
  path: '/app-rules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmployeesJoinRequestsRoute =
  AuthenticatedEmployeesJoinRequestsRouteImport.update({
    id: '/join-requests',
    path: '/join-requests',
    getParentRoute: () => AuthenticatedEmployeesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/employee-scheduling': typeof EmployeeSchedulingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shift-trading': typeof ShiftTradingRoute
  '/time-clock': typeof TimeClockRoute
  '/time-off-management': typeof TimeOffManagementRoute
  '/workforce-management': typeof WorkforceManagementRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/app-rules': typeof AuthenticatedAppRulesRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/organization': typeof AuthenticatedOrganizationRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/punch-corrections': typeof AuthenticatedPunchCorrectionsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/schedule-sheet': typeof AuthenticatedScheduleSheetRoute
  '/schedule-templates': typeof AuthenticatedScheduleTemplatesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shared-clock-in': typeof AuthenticatedSharedClockInRoute
  '/time-off': typeof AuthenticatedTimeOffRoute
  '/timecards': typeof AuthenticatedTimecardsRoute
  '/timeclock': typeof AuthenticatedTimeclockRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/whos-in': typeof AuthenticatedWhosInRoute
  '/worksite': typeof AuthenticatedWorksiteRoute
  '/clock/$token': typeof ClockTokenRoute
  '/employees/join-requests': typeof AuthenticatedEmployeesJoinRequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/employee-scheduling': typeof EmployeeSchedulingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shift-trading': typeof ShiftTradingRoute
  '/time-clock': typeof TimeClockRoute
  '/time-off-management': typeof TimeOffManagementRoute
  '/workforce-management': typeof WorkforceManagementRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/app-rules': typeof AuthenticatedAppRulesRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/organization': typeof AuthenticatedOrganizationRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/punch-corrections': typeof AuthenticatedPunchCorrectionsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/schedule-sheet': typeof AuthenticatedScheduleSheetRoute
  '/schedule-templates': typeof AuthenticatedScheduleTemplatesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shared-clock-in': typeof AuthenticatedSharedClockInRoute
  '/time-off': typeof AuthenticatedTimeOffRoute
  '/timecards': typeof AuthenticatedTimecardsRoute
  '/timeclock': typeof AuthenticatedTimeclockRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/whos-in': typeof AuthenticatedWhosInRoute
  '/worksite': typeof AuthenticatedWorksiteRoute
  '/clock/$token': typeof ClockTokenRoute
  '/employees/join-requests': typeof AuthenticatedEmployeesJoinRequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/employee-scheduling': typeof EmployeeSchedulingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/shift-trading': typeof ShiftTradingRoute
  '/time-clock': typeof TimeClockRoute
  '/time-off-management': typeof TimeOffManagementRoute
  '/workforce-management': typeof WorkforceManagementRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/app-rules': typeof AuthenticatedAppRulesRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/availability': typeof AuthenticatedAvailabilityRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/organization': typeof AuthenticatedOrganizationRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRoute
  '/_authenticated/punch-corrections': typeof AuthenticatedPunchCorrectionsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/schedule-sheet': typeof AuthenticatedScheduleSheetRoute
  '/_authenticated/schedule-templates': typeof AuthenticatedScheduleTemplatesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shared-clock-in': typeof AuthenticatedSharedClockInRoute
  '/_authenticated/time-off': typeof AuthenticatedTimeOffRoute
  '/_authenticated/timecards': typeof AuthenticatedTimecardsRoute
  '/_authenticated/timeclock': typeof AuthenticatedTimeclockRoute
  '/_authenticated/trades': typeof AuthenticatedTradesRoute
  '/_authenticated/whos-in': typeof AuthenticatedWhosInRoute
  '/_authenticated/worksite': typeof AuthenticatedWorksiteRoute
  '/clock/$token': typeof ClockTokenRoute
  '/_authenticated/employees/join-requests': typeof AuthenticatedEmployeesJoinRequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/employee-scheduling'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/reset-password'
    | '/shift-trading'
    | '/time-clock'
    | '/time-off-management'
    | '/workforce-management'
    | '/accounts'
    | '/app-rules'
    | '/audit-log'
    | '/availability'
    | '/billing'
    | '/companies'
    | '/dashboard'
    | '/employees'
    | '/messages'
    | '/organization'
    | '/platform'
    | '/punch-corrections'
    | '/reports'
    | '/schedule'
    | '/schedule-sheet'
    | '/schedule-templates'
    | '/settings'
    | '/shared-clock-in'
    | '/time-off'
    | '/timecards'
    | '/timeclock'
    | '/trades'
    | '/whos-in'
    | '/worksite'
    | '/clock/$token'
    | '/employees/join-requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/employee-scheduling'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/reset-password'
    | '/shift-trading'
    | '/time-clock'
    | '/time-off-management'
    | '/workforce-management'
    | '/accounts'
    | '/app-rules'
    | '/audit-log'
    | '/availability'
    | '/billing'
    | '/companies'
    | '/dashboard'
    | '/employees'
    | '/messages'
    | '/organization'
    | '/platform'
    | '/punch-corrections'
    | '/reports'
    | '/schedule'
    | '/schedule-sheet'
    | '/schedule-templates'
    | '/settings'
    | '/shared-clock-in'
    | '/time-off'
    | '/timecards'
    | '/timeclock'
    | '/trades'
    | '/whos-in'
    | '/worksite'
    | '/clock/$token'
    | '/employees/join-requests'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/employee-scheduling'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/reset-password'
    | '/shift-trading'
    | '/time-clock'
    | '/time-off-management'
    | '/workforce-management'
    | '/_authenticated/accounts'
    | '/_authenticated/app-rules'
    | '/_authenticated/audit-log'
    | '/_authenticated/availability'
    | '/_authenticated/billing'
    | '/_authenticated/companies'
    | '/_authenticated/dashboard'
    | '/_authenticated/employees'
    | '/_authenticated/messages'
    | '/_authenticated/organization'
    | '/_authenticated/platform'
    | '/_authenticated/punch-corrections'
    | '/_authenticated/reports'
    | '/_authenticated/schedule'
    | '/_authenticated/schedule-sheet'
    | '/_authenticated/schedule-templates'
    | '/_authenticated/settings'
    | '/_authenticated/shared-clock-in'
    | '/_authenticated/time-off'
    | '/_authenticated/timecards'
    | '/_authenticated/timeclock'
    | '/_authenticated/trades'
    | '/_authenticated/whos-in'
    | '/_authenticated/worksite'
    | '/clock/$token'
    | '/_authenticated/employees/join-requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  EmployeeSchedulingRoute: typeof EmployeeSchedulingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ShiftTradingRoute: typeof ShiftTradingRoute
  TimeClockRoute: typeof TimeClockRoute
  TimeOffManagementRoute: typeof TimeOffManagementRoute
  WorkforceManagementRoute: typeof WorkforceManagementRoute
  ClockTokenRoute: typeof ClockTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workforce-management': {
      id: '/workforce-management'
      path: '/workforce-management'
      fullPath: '/workforce-management'
      preLoaderRoute: typeof WorkforceManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-off-management': {
      id: '/time-off-management'
      path: '/time-off-management'
      fullPath: '/time-off-management'
      preLoaderRoute: typeof TimeOffManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-clock': {
      id: '/time-clock'
      path: '/time-clock'
      fullPath: '/time-clock'
      preLoaderRoute: typeof TimeClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shift-trading': {
      id: '/shift-trading'
      path: '/shift-trading'
      fullPath: '/shift-trading'
      preLoaderRoute: typeof ShiftTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-scheduling': {
      id: '/employee-scheduling'
      path: '/employee-scheduling'
      fullPath: '/employee-scheduling'
      preLoaderRoute: typeof EmployeeSchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clock/$token': {
      id: '/clock/$token'
      path: '/clock/$token'
      fullPath: '/clock/$token'
      preLoaderRoute: typeof ClockTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/worksite': {
      id: '/_authenticated/worksite'
      path: '/worksite'
      fullPath: '/worksite'
      preLoaderRoute: typeof AuthenticatedWorksiteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/whos-in': {
      id: '/_authenticated/whos-in'
      path: '/whos-in'
      fullPath: '/whos-in'
      preLoaderRoute: typeof AuthenticatedWhosInRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trades': {
      id: '/_authenticated/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthenticatedTradesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/timeclock': {
      id: '/_authenticated/timeclock'
      path: '/timeclock'
      fullPath: '/timeclock'
      preLoaderRoute: typeof AuthenticatedTimeclockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/timecards': {
      id: '/_authenticated/timecards'
      path: '/timecards'
      fullPath: '/timecards'
      preLoaderRoute: typeof AuthenticatedTimecardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/time-off': {
      id: '/_authenticated/time-off'
      path: '/time-off'
      fullPath: '/time-off'
      preLoaderRoute: typeof AuthenticatedTimeOffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shared-clock-in': {
      id: '/_authenticated/shared-clock-in'
      path: '/shared-clock-in'
      fullPath: '/shared-clock-in'
      preLoaderRoute: typeof AuthenticatedSharedClockInRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule-templates': {
      id: '/_authenticated/schedule-templates'
      path: '/schedule-templates'
      fullPath: '/schedule-templates'
      preLoaderRoute: typeof AuthenticatedScheduleTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule-sheet': {
      id: '/_authenticated/schedule-sheet'
      path: '/schedule-sheet'
      fullPath: '/schedule-sheet'
      preLoaderRoute: typeof AuthenticatedScheduleSheetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/punch-corrections': {
      id: '/_authenticated/punch-corrections'
      path: '/punch-corrections'
      fullPath: '/punch-corrections'
      preLoaderRoute: typeof AuthenticatedPunchCorrectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organization': {
      id: '/_authenticated/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AuthenticatedOrganizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/availability': {
      id: '/_authenticated/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AuthenticatedAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app-rules': {
      id: '/_authenticated/app-rules'
      path: '/app-rules'
      fullPath: '/app-rules'
      preLoaderRoute: typeof AuthenticatedAppRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees/join-requests': {
      id: '/_authenticated/employees/join-requests'
      path: '/join-requests'
      fullPath: '/employees/join-requests'
      preLoaderRoute: typeof AuthenticatedEmployeesJoinRequestsRouteImport
      parentRoute: typeof AuthenticatedEmployeesRoute
    }
  }
}

interface AuthenticatedEmployeesRouteChildren {
  AuthenticatedEmployeesJoinRequestsRoute: typeof AuthenticatedEmployeesJoinRequestsRoute
}

const AuthenticatedEmployeesRouteChildren: AuthenticatedEmployeesRouteChildren =
  {
    AuthenticatedEmployeesJoinRequestsRoute:
      AuthenticatedEmployeesJoinRequestsRoute,
  }

const AuthenticatedEmployeesRouteWithChildren =
  AuthenticatedEmployeesRoute._addFileChildren(
    AuthenticatedEmployeesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAppRulesRoute: typeof AuthenticatedAppRulesRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedAvailabilityRoute: typeof AuthenticatedAvailabilityRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedOrganizationRoute: typeof AuthenticatedOrganizationRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRoute
  AuthenticatedPunchCorrectionsRoute: typeof AuthenticatedPunchCorrectionsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedScheduleSheetRoute: typeof AuthenticatedScheduleSheetRoute
  AuthenticatedScheduleTemplatesRoute: typeof AuthenticatedScheduleTemplatesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSharedClockInRoute: typeof AuthenticatedSharedClockInRoute
  AuthenticatedTimeOffRoute: typeof AuthenticatedTimeOffRoute
  AuthenticatedTimecardsRoute: typeof AuthenticatedTimecardsRoute
  AuthenticatedTimeclockRoute: typeof AuthenticatedTimeclockRoute
  AuthenticatedTradesRoute: typeof AuthenticatedTradesRoute
  AuthenticatedWhosInRoute: typeof AuthenticatedWhosInRoute
  AuthenticatedWorksiteRoute: typeof AuthenticatedWorksiteRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAppRulesRoute: AuthenticatedAppRulesRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedAvailabilityRoute: AuthenticatedAvailabilityRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedOrganizationRoute: AuthenticatedOrganizationRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRoute,
  AuthenticatedPunchCorrectionsRoute: AuthenticatedPunchCorrectionsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedScheduleSheetRoute: AuthenticatedScheduleSheetRoute,
  AuthenticatedScheduleTemplatesRoute: AuthenticatedScheduleTemplatesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSharedClockInRoute: AuthenticatedSharedClockInRoute,
  AuthenticatedTimeOffRoute: AuthenticatedTimeOffRoute,
  AuthenticatedTimecardsRoute: AuthenticatedTimecardsRoute,
  AuthenticatedTimeclockRoute: AuthenticatedTimeclockRoute,
  AuthenticatedTradesRoute: AuthenticatedTradesRoute,
  AuthenticatedWhosInRoute: AuthenticatedWhosInRoute,
  AuthenticatedWorksiteRoute: AuthenticatedWorksiteRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  EmployeeSchedulingRoute: EmployeeSchedulingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ShiftTradingRoute: ShiftTradingRoute,
  TimeClockRoute: TimeClockRoute,
  TimeOffManagementRoute: TimeOffManagementRoute,
  WorkforceManagementRoute: WorkforceManagementRoute,
  ClockTokenRoute: ClockTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
